server:
  port: ${PORT:${SERVER_PORT:0}}
spring:
  application:
    name: api-movie
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/movie-dev
    username: root       #usr-movie
    password: 127465211q      #pwd-movie
  jpa:
    hibernate.ddl-auto: update
    generate-ddl: true
    show-sql: true
